#kennedy becher
#problem 1
"""If we list all the natural numbers below 10 that are multiples of
3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23."""

Find the sum of all the multiples of 3 or 5 below 1000.
all_sum = 0 #setting sum to zero
for i in range(1000): #setting range and for statement
    if (i%3 ==0 or i%5 ==0): # finding multiples of 3 & 5
        all_sum = all_sum + i 
print(all_sum)


#problem 2
"""Each new term in the Fibonacci sequence is generated by adding 
the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values
do not exceed four million, find the sum of the even-valued terms."""
def Fibonacci(p1):
    p1 = input
    if ((p1==0) or (p1==1)):
        return 1
    else:
        return ((Fibonacci(p1-1))+(Fibonacci(p1-2)))
a =0
all_sum = 0
while (Fibonacci(a))<4000000:
    if (((Fibonacci(a))%2)==0):
        all_sum+= Fibonacci(a)
print(all_sum)
Fibonacci()

#problem 3
"""The prime factors of 13195 are 5, 7, 13 and 29.
What is the largest prime factor of the number 600851475143 ?"""
x = 2
y = 600851475143
while x * x < y:
    while y % x == 0:
        y = y / x
    x = x + 1
print(y) 


